language: php
services: mysql

#travis usually doesn't build gh-pages branch, but we want it to for testing
#and since it is a white list we have to also whitelist everythign else
branches:
  only:
    - gh-pages
    - /^.*$/

matrix:
  fast_finish: true
  allow_failures:
  - env: BEHAT_PROFILE='osxsafari'

php:
- '5.4'

env:
  global:
  - SAUCE_USERNAME="ilios"
  #SAUCE_ACCESS_KEY
  - secure: TWX+vAZYyU+m4Eur8Eyuo39feAU/8sCVqoW3QLdmP0umGSaOHxrTrQuX4lGNUOV1nLMedAQl/7FVryl4eBJwhth8iQ9xjDIdRCshN+lvQfEGB6D91FrgJ7ZoR/QnKxcHddFzaGXAlglVZE8JT5Ljp36tyKbbNoEt0YBgwSnYxW0=

  matrix:
  - BEHAT_PROFILE='default'
  - BEHAT_PROFILE='win7ie9'
  - BEHAT_PROFILE='win8ie11'
  - BEHAT_PROFILE='osxsafari'

addons:
  hosts:
  - localtest
  sauce_connect: true

install:
- composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}

before_script:
- php -S 0.0.0.0:8000 -t ${TRAVIS_BUILD_DIR} > /dev/null &
- sleep 3

script:
- if [ "$SAUCE_ACCESS_KEY" ] ; then (${TRAVIS_BUILD_DIR}/bin/behat -c ${TRAVIS_BUILD_DIR}/tests/behat.yml --profile $BEHAT_PROFILE); fi
